### ISSUE TITLE
please remove .idea/ folder from git.. cannot checkout

### ISSUE THREAD

**Issue by syzer** [node4good/opinion#2]

**Comment by refack** [comment]
You are raising an interesting issue...
I'm not sure why this will cause your clone to fail, as this is a legitimate directory name even on Windows.
On the one hand it's metadata and is not directly related to the code...
On the other hand it is trackable and versionable, and may help others who use IDEA derivatives.
.
.
.
I'm sorry but for now it will stay in. Feel free to fork and remove for you own use.

**Comment by syzer** [comment]
`and may help others who use IDEA derivatives.`
IMHO quite the opposite.. IDEA my not start on different architecture it this folder is present.
also IMHO pushing to git .dotfiles.... .... ehh
